site :opscode

cookbook 'apt'
cookbook 'ruby_build', git: 'https://github.com/fnichol/chef-ruby_build.git'
cookbook 'rbenv', :git => 'https://github.com/jjshoe/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'Tiny.House', git: 'https://github.com/jjshoe/Tiny.House-chef'